### ISSUE TITLE
Plugin update

### ISSUE THREAD

**Issue by MandarinTangerine** [TheThunderLizard/bronto_woocommerce#2]
This is a query if there's a plugin update of the BRONTO WOOCOMMERCE PLUGIN https://github.com/TheThunderLizard/bronto_woocommerce

**Comment by MandarinTangerine** [comment]
Just to followup about the query regarding the BRONTO WOOCOMMERCE PLUGIN https://github.com/TheThunderLizard/bronto_woocommerce

**Comment by TheThunderLizard** [comment]
Hi @MandarinTangerine Is there a particular issue that you are requesting an update for?

**Comment by TheThunderLizard** [comment]
We're going to close this issue since there's no stated concern.  Should you wish to re-open, we would be happy to review the issue.
